/**
 * 
 */
package v2.org.analysis.apihandle.winapi.msvcrt.functions;

import v2.org.analysis.apihandle.winapi.msvcrt.MSVCRTAPI;
import v2.org.analysis.apihandle.winapi.msvcrt.MSVCRTDLL;
import v2.org.analysis.value.LongValue;

/**
 * Generate random number
 * 
 * Returns a pseudo-random integral number in the range between 0 and
 * RAND_MAX.
 * 
 * This number is generated by an algorithm that returns a sequence of
 * apparently non-related numbers each time it is called. This algorithm
 * uses a seed to generate the series, which should be initialized to some
 * distinctive value using function srand.
 * 
 * @return An integer value between 0 and RAND_MAX.
 * 
 * @author YenNLH
 *
 */
public class rand extends MSVCRTAPI {

	public rand() {
		super();
		NUM_OF_PARMS = 0;
	}
	
	@Override
	public void execute() {
		int ret = MSVCRTDLL.INSTANCE.rand();
		
		register.mov("eax", new LongValue(ret));
	}

}
